# ruff: noqa: E501
# Generated by Django 6.0.1 on 2026-03-23 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_tasks'),
        ('tasks', '0006_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_projects', to='projects.project'),
        ),
    ]
