# ruff: noqa: E501

# Generated by Django 6.0.1 on 2026-03-13 14:31

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(
                    default=datetime.date.today, 
                    help_text='Please use the following format: <em>YYYY-MM-DD</em>.'
                )),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_author', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_executor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
