# Generated by Django 6.0.1 on 2026-03-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('projects', '0002_project_created_at_project_deadline_and_more'),
        ('tasks', '0006_task_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='projects', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='labels.label'),
        ),
    ]
