# ruff: noqa: E501
# Generated by Django 6.0.1 on 2026-03-18 18:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('projects', '0003_alter_project_options_project_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='projects', to='labels.label'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
    ]
