# ruff: noqa: E501
# Generated by Django 6.0.1 on 2026-03-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_labels_alter_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
    ]
