# Generated by Django 5.2.7 on 2025-12-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusIndexView',
            new_name='Status',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
