# Generated by Django 6.0.1 on 2026-03-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(
                max_length=100, 
                unique=True, 
                verbose_name='Status'
            ),
        ),
    ]
